---
title: "Forecast scores"
format: html
editor: visual
---

## Load data

```{r}
library(tidyverse)

#Load saved scores
#Generated by 01 - Score forecasts.qmd
scores <- read_csv("scores.csv", show_col_types = F)
scores_format_all <- read_csv("scores_format_all.csv")
```

## Plot

```{r}
desat <- function(cols, sat=0.5) {
    X <- diag(c(1, sat, 1)) %*% rgb2hsv(col2rgb(cols))
    hsv(X[1,], X[2,], X[3,])
}

jpeg("../figures/RMSE_rep_comb.jpg", width = 5, height = 2.5, units = "in", res = 300)
rmse <- scores_format_all %>%
  mutate(Veg = case_match(Veg,
                          "C3" ~ "C[3]",
                          "C4" ~ "C[4]")) %>%
  filter(CO2Treat == "Amb",
         horizon == 6) %>%
  group_by(horizon, model_id, Temp, CO2Treat, Veg, Type, site_id) %>%
  summarize(rmse = Metrics::rmse(observation, mean),
            n = n(),
            .groups = "drop") %>%
  group_by(horizon, model_id, Temp, CO2Treat, Veg) %>%
  mutate(rmse = (rmse[Type == "Rep_comb"] - rmse) / rmse * 100,
         Temp = as.factor(Temp)
         ) %>%
  filter(!Type == "Rep_comb") 

rmse %>%
  ggplot(aes(x = Temp, 
             y = rmse)) +
  geom_hline(yintercept = 0, color = "grey50") +
  geom_jitter(aes(color = model_id, group = CO2Treat), 
              width = 0.3,
              size = 1) +
  geom_boxplot(outliers = F, alpha = 0, linewidth = 0.3) +
  ggh4x::facet_nested(.~Veg, 
                      space = "free_x", scales = "free_x",
                      labeller = label_parsed)+
  scale_linetype_manual(values = c("solid", "31"), 
                     labels = c("Ambient","Elevated"))+
  scale_color_manual(values = colorspace::lighten(desat(viridis::viridis(11), 0.3), 0.6))+
  xlab("Temperature treatment (ºC above ambient)")+
  ylab(expression(atop("Percent change in RMSE","using spatial average")))+
  theme_bw(base_size = 10)+
  guides(color = guide_legend(byrow = TRUE, title = "Model"))+
  theme(strip.background = element_rect(fill = "white",
                                        color = "grey85"),
        legend.key.height = unit(0.7, 'lines'),
        legend.text = element_text(margin = ggplot2::margin(t = 0, b = 0)),
        panel.grid.major.x = element_blank())
dev.off()


jpeg("../figures/RMSE_ambCO2_comb_reps.jpg", width = 5, height = 2.5, units = "in", res = 300)
rmse_raw <- scores_format_all %>%
  filter(horizon %in% c(6),
         CO2Treat == "Amb",
         Type == "Rep_comb") %>%
  mutate(CO2Treat = case_match(CO2Treat,
                               "Amb" ~ "Ambient~CO[2]",
                               "Elev" ~ "Elevated~CO[2]"),
         Veg = case_match(Veg,
                          "C3" ~ "C[3]",
                          "C4" ~ "C[4]"),) %>%
  group_by(horizon, site_id, model_id, Temp, year, CO2Treat, Veg) %>%
  summarize(rmse = Metrics::rmse(observation, mean),
            n = n(),
            .groups = "drop") %>%
  mutate(Temp = as.factor(Temp)) 

rmse_raw %>%
  ggplot(aes(x = Temp, 
             y = rmse)) +
  geom_jitter(aes(color = model_id, group = CO2Treat), 
              width = 0.3,
              size = 1) +
  geom_boxplot(outliers = F, alpha = 0, linewidth = 0.3) +
  ggh4x::facet_nested(.~Veg, 
                      space = "free_x", scales = "free_x",
                      labeller = label_parsed)+
  scale_linetype_manual(values = c("solid", "31"), 
                     labels = c("Ambient","Elevated"))+
  scale_color_manual(values = colorspace::lighten(desat(viridis::viridis(11), 0.3), 0.6))+
  xlab("Temperature treatment (ºC above ambient)")+
  ylab(expression(atop("Error of 6-month forecast",(RMSE*";"~µmol/m^{2}/d))))+
  theme_bw(base_size = 10)+
  guides(color = guide_legend(byrow = TRUE, title = "Model"))+
  theme(strip.background = element_rect(fill = "white",
                                        color = "grey85"),
        legend.key.height = unit(0.7, 'lines'),
        legend.text = element_text(margin = ggplot2::margin(t = 0, b = 0)),
        panel.grid.major.x = element_blank())
dev.off()

jpeg("../figures/RMSE_ambCO2_comb_reps_both.jpg", width = 5, height = 4, units = "in", res = 300)
rmse %>%
  mutate(type = paste0(expression(atop("Percent change in RMSE","using spatial average")))) %>%
  rbind(rmse_raw %>% mutate(type = paste0(expression(atop("Error of 6-month forecast",(RMSE*";"~µmol/m^{2}/d)))))) %>%
  mutate(type = factor(type, levels = rev(unique(type)))) %>%
  ggplot(aes(x = Temp, 
             y = rmse)) +
  geom_hline(aes(yintercept = y), color = "grey50", data = data.frame(y = 0, type = paste0(expression(atop("Percent change in RMSE","using spatial average"))))) +
  geom_jitter(aes(color = model_id, group = CO2Treat), 
              width = 0.3,
              size = 1) +
  geom_boxplot(outliers = F, alpha = 0, linewidth = 0.3) +
  ggh4x::facet_nested(type~Veg, 
                      scales = "free",
                      labeller = label_parsed)+
  scale_linetype_manual(values = c("solid", "31"), 
                     labels = c("Ambient","Elevated"))+
  scale_color_manual(values = colorspace::lighten(desat(viridis::viridis(11), 0.3), 0.6))+
  xlab("Temperature treatment (ºC above ambient)")+
  ylab(expression(atop("Percent change in RMSE","using spatial average")))+
  theme_bw(base_size = 10)+
  guides(color = guide_legend(byrow = TRUE, title = "Model"))+
  theme(strip.background = element_rect(fill = "white",
                                        color = "grey85"),
        legend.key.height = unit(0.7, 'lines'),
        legend.text = element_text(margin = ggplot2::margin(t = 0, b = 0)),
        panel.grid.major.x = element_blank())
dev.off()
```

## Stats

```{r}
rmse %>%
  ungroup() %>%
  summarize(mean(rmse))

rmse %>%
  group_by(Temp, Veg) %>%
  summarize(mean(rmse))
```
