---
title: "Forecast scores"
format: html
editor: visual
---

## Load data

```{r}
library(tidyverse)

#Load saved scores
#Generated by 01 - Score forecasts.qmd
scores <- read_csv("scores.csv", show_col_types = F)
scores_format_all <- read_csv("scores_format_all.csv")

desat <- function(cols, sat=0.5) {
    X <- diag(c(1, sat, 1)) %*% rgb2hsv(col2rgb(cols))
    hsv(X[1,], X[2,], X[3,])
}
```

## Horizon

```{r}
jpeg("../figures/horizon.jpg", res = 300, units = "in", width = 4, height = 4)
scores_format %>%
  group_by(horizon, site_id, Temp, year, CO2Treat, Veg) %>%
  mutate(mean_obs = mean(observation, na.rm = T),
         sd = sd(observation, na.rm = T),
         n = n(),
         .groups = "drop") %>%
  group_by(horizon, site_id, model_id, Temp, year, CO2Treat, Veg, model_type) %>%
  summarize(rmse = Metrics::rmse(observation, mean),
            mean = unique(mean_obs),
            n = n(),
            .groups = "drop") %>%
  ggplot(aes(x = horizon, 
             y = rmse,
             color = model_id)) +
  #geom_point(alpha = 0.1)+
  geom_smooth(se = F)+
  ggh4x::facet_nested(Temp~Veg, scales = "free_y", independent = "y")+
  xlab("Horizon (months)")+
  scale_color_viridis_d(name = "Model")+
  theme_bw(base_size = 10)
dev.off()
```

## Confidence

```{r}
jpeg("../figures/confidence.jpg", res = 300, units = "in", width = 4, height = 4)
scores_format %>%
  filter(horizon == 6) %>%
  mutate(in_95 = observation > quantile02.5 & observation < quantile97.5,
         in_80 = observation > quantile10 & observation < quantile90) %>%
  group_by(Temp, CO2Treat, horizon, Veg, model_id) %>%
  summarize(pct_95 = sum(in_95)/n()*100,
            pct_80 = sum(in_80)/n()*100) %>%
  pivot_longer(c(pct_80, pct_95)) %>%
  mutate(Temp = as.factor(Temp)) %>%
  ggplot(aes(x = Temp, 
             y = value)) +
  geom_hline(aes(yintercept = val), 
             data = data.frame(val = c(80, 95), 
                               name = c("pct_80", "pct_95")),
             lty = "11")+
  geom_jitter(aes(color = model_id, group = CO2Treat), 
              width = 0.3,
              size = 1) +
  geom_boxplot(outliers = F, alpha = 0, linewidth = 0.3) +
  ggh4x::facet_nested(name~Veg+CO2Treat, 
                      space = "free_x", scales = "free",
                      labeller = label_parsed)+
  scale_linetype_manual(values = c("solid", "31"), 
                     labels = c("Ambient","Elevated"))+
  scale_color_manual(values = colorspace::lighten(desat(viridis::viridis(10), 0.3), 0.6))+
  xlab("Temperature treatment\n(ºC above ambient)")+
  ylab("Percentage of observations within confidence interval")+
  theme_bw(base_size = 10)+
  guides(color = guide_legend(byrow = TRUE, title = "Model"),
         linetype = guide_legend(byrow = TRUE,
                     title = expression(CO[2]~Treatment)))+
  theme(strip.background = element_rect(fill = "white",
                                        color = "grey85"),
        legend.key.height = unit(0.7, 'lines'),
        legend.text = element_text(margin = ggplot2::margin(t = 0, b = 0)),
        panel.grid.major.x = element_blank())
dev.off()
```
