---
title: "Initial data exploration"
author: "Abby Lewis"
date: "2024-08-21"
output: html_document
---

Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(rtide)
#scales?

drivers <- read_csv("../Raw_data/GENX_SD_Export_Waterlevel_2021-05-06_to_2022-12-30_derived_clean_btemps.csv", 
                    show_col_types = F)
met <- read_csv("../processed_data/met_output.csv")

met %>%
  ggplot (aes )
```

How do we relate sensor height to tide height?
- About an hour delay
- High surge is from water blown from Chesapeake 


```{r}
min <- as.Date("2021-08-01")
max <- as.Date("2021-09-01")

data <- rtide::tide_height(
  "Annapolis (US Naval Academy), Severn River, Maryland",
  from = min, to = max,
  minutes = 10L, tz = "UTC"
)
#library(rtide)

tide_noaa <- read_csv("https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?product=predictions&application=NOS.COOPS.TAC.WL&begin_date=20210801&end_date=20210901&datum=MLLW&station=8575579&time_zone=GMT&units=metric&interval=hilo&format=csv")

data %>%
  ggplot() +
  geom_line(aes(x = DateTime, y = TideHeight)) +
  geom_line(aes(x = `Date Time`, y = Prediction), data = tide_noaa, color = "blue")+
  scale_y_continuous(name = "Tide Height (m)") +
  #geom_col(aes(x= as.POSIXct(Date), y = rain_cm_tot), data = met %>% filter(Date > min, Date < max)) +
  geom_line(data = drivers %>% filter(time2 > "2021-08-01", time2 < "2021-09-01"), aes(x = time2, y = corrected_depth/100), color = "red")

tide_noaa %>%
  mutate(Date = as.Date(`Date Time`)) %>%
  group_by(Date) %>%
  mutate(Prediction = mean(Prediction, na.rm = TRUE)) %>%
  ggplot(aes(x = Date, y = Prediction)) +
  geom_point()

data <- rtide::tide_height(
  "Annapolis (US Naval Academy), Severn River, Maryland",
  from = as.Date(min(drivers$time2)), to = as.Date(max(drivers$time2)),
  minutes = 60, tz = "UTC"
)

data %>%
  ggplot(aes(x = DateTime, y = TideHeight)) +
  geom_line() +
  scale_y_continuous(name = "Tide Height (m)") +
  geom_line(data = drivers, aes(x = time2, y = corrected_depth/100), color = "red")
```

How do we relate soil temp to air temp?

```{r}
drivers %>%
  filter(!is.na(time2), !is.na(chamber_treatment)) %>%
  ggplot(aes(x = time2, group = chamber_treatment)) +
  geom_line(aes(y = temp), color = "red") +
  geom_line(aes(y = therm10c)) +
  geom_line(aes(y = therm25c), color = "blue") +
  facet_wrap(~chamber_treatment)

drivers %>%
  filter(!is.na(time2), !is.na(chamber_treatment),
         time2>as.POSIXct("2022-07-01"),
         time2<as.POSIXct("2022-07-15")) %>%
  ggplot(aes(x = time2, group = chamber_treatment)) +
  geom_line(aes(y = temp), color = "red") +
  geom_line(aes(y = therm10c)) +
  geom_line(aes(y = therm25c), color = "blue") +
  facet_wrap(~chamber_treatment)
```

