---
title: "CMEM"
author: "Abby Lewis"
date: "2024-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#import elevation data to environment.
elevation<- read.table(file="./CMEM Eden Landing Example/EDENLAND082620.txt",sep=",")

a <- elevation %>%
  rename(record=V1,
         S1=V2,
         S2=V3,
         elevation=V4,
         edcv=V5) %>%
  slice(-25) %>%
  summarise(elev = mean(elevation)*100) %>%
  pull(.)

rootDepthMax = 30
omPackingDensity = 0.085
mineralPackingDensity = 1.99
rootPackingDensity = omPackingDensity

moonscapeCohorts <- data.frame(age=rep(0, round(rootDepthMax+0.6)), # set all ages to 0
                      fast_OM=rep(0, round(rootDepthMax+0.6)), # Note that fast, slow, and root mass initial conditions are all set to 0
                      slow_OM=rep(0, round(rootDepthMax+0.6)),
                      respired_OM=rep(0, round(rootDepthMax+0.6)),
                      mineral=rep(mineralPackingDensity,round(rootDepthMax+0.6)), # Mineral mass is 100% so equal to the packing density
                      root_mass=rep(0,round(rootDepthMax+0.6)),
                      layer_top=0:((round(rootDepthMax+0.6)-1)), # 1 cm depth increments
                      layer_bottom=1:round(rootDepthMax+0.6)) %>% 
  dplyr::mutate(cumCohortVol = cumsum(layer_bottom-layer_top))

startYear=2010

memCohortExample2 <- runCohortMem(startYear = 2010,
                                     relSeaLevelRiseInit = 0.24, 
                                     relSeaLevelRiseTotal = 40, 
                                     initElv = 165, 
                                     meanSeaLevel = 110, 
                                     meanSeaLevelDatum = 98.1, 
                                     meanHighWaterDatum = 194.7, 
                                     meanHighHighWaterDatum = 213.3, 
                                     meanHighHighWaterSpringDatum = NA, 
                                     suspendedSediment = .000045, 
                                     lunarNodalAmp = 2.5, 
                                     lunarNodalPhase = 2011.181, 
                                     nFloods = 705.79, 
                                     bMax = 0.09, 
                                     zVegMin = 80, 
                                     zVegMax = 350, 
                                     zVegPeak = NA, 
                                     plantElevationType = "orthometric",
                                     rootToShoot = 2, 
                                     rootTurnover = 0.5, 
                                     abovegroundTurnover = NA, 
                                     speciesCode = NA, 
                                     rootDepthMax = 30, 
                                     shape = "linear", 
                                     omDecayRate = 0.2, 
                                     recalcitrantFrac = 0.35, 
                                     captureRate = 0.275, 
                                     omPackingDensity = 0.085, 
                                     mineralPackingDensity = 1.99, 
                                     initialCohorts = moonscapeCohorts, 
                                     uplandCohorts = NA, 
                                     supertidalCohorts = NA, 
                                     supertidalSedimentInput = NA
                                     )

slow <- tapply(memCohortExample2$cohorts$slow_OM,
           memCohortExample2$cohorts$year,
           FUN = mean)
slow
fast <- tapply(memCohortExample2$cohorts$fast_OM,
           memCohortExample2$cohorts$year,
           FUN = mean)
fast
resp <-tapply(memCohortExample2$cohorts$respired_OM,
           memCohortExample2$cohorts$year,
           FUN = mean)
resp

y<- tribble(
  ~MEM_Variable, ~Equiv._PEPRMNT_C_Pool, ~PEPRMNT_Variable, ~theta_element,
  "Slow_OM", "Soil Organic Carbon (SOC) Pool", "S2", "theta[5]",
  "Fast_OM", "Labile Carbon Pool", "S1", "theta[6]"
)

kable(y)
```

