---
title: "Run PEPRMT-Tidal"
output: html_document
date: "2023-10-19"
author: Patty Oikawa
email: patty.oikawa@gmail.com
---

Load packages

```{r setup, echo=FALSE, message=FALSE}
library(pacman)
p_load(R.matlab, here, tidyverse, FME, Metrics, lubridate, gridExtra)
source("run_PEPRMT.R")
source("PEPRMT_GPP_FINAL.R")
source("PEPRMT_CH4_FINAL_ASL.R")
source("PEPRMT_Reco_FINAL.R")
```

Load data

```{r}
target <- read_csv("peprmt_target.csv") %>%
  as.data.frame() %>%
  mutate(NO3_mg_L = 0.062, #Copied from US_PLM
         WTD_cm = -WTD_cm) %>% #Switch this when you update Load/Format data.Rmd
  group_by(site) %>%
  mutate(SOM_MEM_gC_m3 = ifelse(DOY == min(DOY),
                                SOM_MEM_gC_m3,
                                0))
ch4_validation <- read_csv("ch4_validation.csv") %>%
  as.data.frame()
example <- read_csv("All_sites_master.csv") 

target %>%
  mutate(site_char = "gcrew") %>%
  full_join(example) %>%
  pivot_longer(cols = -c(site_char, DOY_disc, DOY, site)) %>%
  filter(!is.na(value),
         !grepl("GPP|CO2|FPAR|Reco", name),
         !value == 0 | !name == "SOM_MEM_gC_m3") %>%
  ggplot(aes(y = site_char, x = value)) +
  geom_boxplot()+
  facet_wrap(~name, scales = "free_x")

ch4_validation %>%
  mutate(site_char = "gcrew") %>%
  full_join(example) %>%
  mutate(ch4_mg_m2_day = ifelse(is.na(CH4_gC_m2_day), CH4_slope_mgC_m2_d, CH4_gC_m2_day * 1000),
         type = ifelse(site_char %in% c("US_STJ", "US_LA1"), "High", "Low")) %>%
  ggplot(aes(x = site_char, y = ch4_mg_m2_day)) +
  geom_boxplot() +
  #facet_grid2(cols = vars(type), scales = "free", independent = "y") + 
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10))

library(ggh4x)
```

Run all modules

```{r}
target_results <- run_PEPRMT(as.data.frame(target))
example_results <- run_PEPRMT(as.data.frame(example))

for(site_x in 1:length(unique(example$site))){
  site1 <- subset(example_results, site == site_x)
  plot <- site1 %>%
    complete(DOY = first(DOY):max(DOY)) %>%
    ggplot(aes(DOY)) +
    geom_line(aes(x = DOY, y = CH4_gC_m2_day, color = "observation"), 
              data = example %>% filter(site == site_x) %>%
                complete(DOY = first(DOY):max(DOY)))+
    geom_line(aes(x = DOY, y = CH4_mod, color = "model"))+
    labs(x = "", y=bquote('CH4 '~ (mgC ~ m^-2 ~ d^-1))) +
    ## To make the plot look prettier
    theme_bw(base_size = 12) +
    ggtitle(unique(example$site_char)[site_x])
  print(plot)
}
```

Plot
```{r}
#make plots for each site
for(site_x in 1:length(unique(target$site))){
  site1 <- subset(target_results, site == site_x)
  plot <- site1 %>%
    complete(DOY = first(DOY):max(DOY)) %>%
    ggplot(aes(DOY)) +
    geom_line(aes(x = DOY, y = CH4_slope_mgC_m2_d, color = "observation"), 
              data = ch4_validation %>% filter(site == site_x) %>%
                complete(DOY = first(DOY):max(DOY)))+
    geom_line(aes(x = DOY, y = CH4_mod*1000, color = "model"))+
    labs(x = "", y=bquote('CH4 '~ (mgC ~ m^-2 ~ d^-1))) +
    ## To make the plot look prettier
    theme_bw(base_size = 12) +
    ggtitle(site_x)
  print(plot)
}
```

Run sensitivity analysis

```{r}
sens_analysis <- function(var, target){
  message(var)
  # Up
  target_modif <- target %>%
    mutate(!!var := !!sym(var) * 1.5)
  target_results_up <- run_PEPRMT(target_modif) %>%
    mutate(var_modif = var,
           modif = "up 50%")
  
  # Down
  target_modif <- target %>%
    mutate(!!var := !!sym(var) * 0.5)
  target_results_down <- run_PEPRMT(target_modif) %>%
    mutate(var_modif = var,
           modif = "down 50%")
  
  bind_rows(target_results_up, target_results_down)
}

sens_vars <- c("Year", "TA_C", "WTD_cm", "PAR_umol_m2_day", "EVI", "LUE", "Wetland_age_years", "Salinity_daily_ave_ppt", "NO3_mg_L", "SOM_MEM_gC_m3")

sens_results <- sens_vars %>%
  map(sens_analysis, target = target) %>%
  bind_rows() 

ch4_add <- data.frame(var_modif = sens_vars,
           site_char = "gcrew",
           modif = "data") %>%
  left_join(ch4_validation %>%
              mutate(site_char = "gcrew")) %>%
  rename(CH4_mod = CH4_slope_mgC_m2_d)

ch4_orig <- data.frame(var_modif = sens_vars,
           site_char = "gcrew",
           modif = "orig") %>%
  left_join(target_results %>%
              mutate(site_char = "gcrew")) %>%
  mutate(CH4_mod = CH4_mod * 1000)

sens_results %>%
  mutate(CH4_mod = CH4_mod * 1000) %>%
  full_join(ch4_add) %>%
  full_join(ch4_orig) %>%
  ggplot(aes(x = modif, y = CH4_mod)) +
  geom_boxplot() +
  facet_wrap(~var_modif, scales = "free_y") +
  coord_cartesian(ylim = c(-20, 50))
```